person:
  age: ${random.int}
  name: 王老${random.value}
  birthday: 2020/12/13
  maps:
    k1: v1
    k2: 13
  boss: false
  dog:
    name: ${person.hello:hello}dog
    age: 2
  list: [1,3,4,5,6]

server:
  port: 8081

spring:
  profiles:
    active: prod
debug: true
---
server:
  port: 8082
spring:
  profiles: dev
---
server:
  port: 8083
spring:
  profiles: prod
